### ISSUE TITLE
Option to allow parser to return only text of main documents

### ISSUE THREAD

**Issue by trevoryann** [chrismattmann/tika-python#168]
I have found some PDF files that have embedded files in them, and would like to extract the text without the attachment. There is no option to do this in the python API. 

The attached PDF file has an embedded attachment that has options for the Adobe distiller tool. These options are in postscript, but included as text along with the main text from the PDF file when parser.from_file is called.

[A_latent_topic_model_for_complete_entity.pdf](https://github.com/chrismattmann/tika-python/files/1577220/A_latent_topic_model_for_complete_entity.pdf)

**Comment by chrismattmann** [comment]
hi, unfortunately this isn't a super high priority right now. One possible way to fix this would be to send me a Pull request that:

1. Adds an option to the _parse method for recursive=True (by default). 
2. Then in _parse you could check to see if recursive is True: if so, call '/rmeta' otherwise call '/meta' and '/meta/text' endPoints.

If you have time and energy I would be happy to commit this enhancement.

**Comment by marcelo-dalmeida** [comment]
It would be good to have a way to not deactivate recursion altogether. 

In my case I would like to extract text from images but not from its annex in a docx file

Seeing from this issue page, I understand this is currently not possible
