### ISSUE TITLE
Tika language detector ever gives "th" for pdf files

### ISSUE THREAD

**Issue by SYNEQUANON** [chrismattmann/tika-python#246]
I have an issue with the use of Tika for language detection. I first remarked that when I parse PDF files, the language was not included in the "metadata part" in most cases.

Thus, I tried to explicitly detect the language and I got in most cases "th" as result, while my documents are in french. Then, I copied the PDF file content in a simple text file and the result was strangely right. 
This is the code I used: 
`from tika import language
print(language.from_file(file))`

Let me notice that I just installed tika with the command `pip install tika` whithout any additional configuration. Is anything wrong in the process I used?

**Comment by chrismattmann** [comment]
can you take this upstream to `dev@tika.apache.org`? Thank you...tika python just uses the output of the Tika API....

**Comment by jjelosua** [comment]
+1 to this, @SYNEQUANON have you posted to the dev mailing list? Can not find it. Also is the language supposed to be part of the default metadata returned by tika 1.22? I have tested with *.txt and *.pdf and did not find the language key in any of those

**Comment by jjelosua** [comment]
I have sent the question to the dev mailing list, here's the response:
`In looking at the source code for this (for the first time?)...it looks
like that endpoint expects UTF-8 text.  It does not parse the file and then
run lang id on the parsed text.` they have updated the wiki to reflect this misunderstanding [https://cwiki.apache.org/confluence/display/TIKA/TikaJAXRS#TikaJAXRS-LanguageResource](https://cwiki.apache.org/confluence/display/TIKA/TikaJAXRS#TikaJAXRS-LanguageResource)

So either we first run the metadata and content extraction and then pass it to the UTF-8 stream to detect language or we just use this endpoint to do what is supposed to be doing not including parsing different filetypes.

Did I read on issue #103 that the metadata endpoint `/rmeta` was supposed to include the language detection...maybe waiting for that to happen can be the best option instead of reinventing the wheel on this wrapper.

**Comment by chrismattmann** [comment]
thanks @jjelosua yeah we are waiting on that in #103 - it may be the best bet, but we have been waiting for a while
