### ISSUE TITLE
Avoiding Page numbers, Footers and headers

### ISSUE THREAD

**Issue by athreyanmks** [chrismattmann/tika-python#313]
I am using tika to extract a pdf with a few hundred pages, often the page number or footer of each page is extracted along with relevant data. Can I configure tika to ignore footers and headers so the continuity of text is not broken.

**Comment by chrismattmann** [comment]
Hmm, you can upstream in the Java version with configuration options that are then passed by Tika server to the downstream python library. I recommend you asking your question on [dev@tika.apache.org](mailto:dev@tika.apache.org)

**Comment by Timoeller** [comment]
Hey @chrismattmann awesome wrapper you created there for tika.

I came across the new tika feature of extracting structured PDF info like headers etc since tika v1.24, see related [tika JIRA](https://issues.apache.org/jira/browse/TIKA-3026). 
How would you enable this feature when using your library? 
Just enabling the `xmlContent=True` wont do the trick in the parser.from_file method...
I tried looking into docs for the `requestOptions` but couldn't figure out a way.

Btw. I am using tika through `docker run -p 9998:9998 apache/tika:1.24.1`

**Comment by chrismattmann** [comment]
thanks @Timoeller - you need to see the config file properties. You can pass a custom config file to your tika server on startup....check out the docs and thanks
