### ISSUE TITLE
tika.TikaClientOnly = True shows warning messages

### ISSUE THREAD

**Issue by Zast996** [chrismattmann/tika-python#326]
Hi everyone,
I'm using the 1.24 version of Tika with Python installed through pip.
Tika is installed on a conda env with python 3.8.5 on Ubuntu 20.04.
I read that if I want to run tika one the localhost without print any check message, I have to use "tika.TikaClientOnly = True"
However, when I start my project, on the cmd it appears the following message:

> 2020-11-24 09:12:45,303 [MainThread  ] [WARNI]  Failed to see startup log message; retrying...

The problem is that this behaviour delays the execution of the project (it freezes for  about 10 seconds).

Many thanks in advance

**Comment by chrismattmann** [comment]
I couldn't replicate this functionality...if I use TikaClientOnly it doesn't use the checkServer method and instead uses the URL referenced one. Are you sure you are setting it correctly? Can you trace in the code as to what the value of that variable is before it calls the checkServer?

**Comment by eLod** [comment]
i think this is a documentation issue, the [README](https://github.com/chrismattmann/tika-python?tab=readme-ov-file#using-client-only-mode) has a misleading code because the set just silently "works" but it is not setting the right variable. the import should be `import tika from tika` (or `tika.tika.TikaClientOnly` should be set).

**Comment by chrismattmann** [comment]
@eLod i will update the README thanks!

**Comment by chrismattmann** [comment]
fixed in https://github.com/chrismattmann/tika-python/commit/9f651c9dc00f46bde364fec69ad97833f97ac671 @eLod
