### ISSUE TITLE
Tika server returned status: 405

### ISSUE THREAD

**Issue by harshgorjiwala** [chrismattmann/tika-python#374]
[MainThread ] [WARNI] Tika server returned status: 405 Traceback (most recent call last)

Every time I try to load python it return this same error.

Even i try to assign environment variable. 

Can someone please let me know how to solve this error.

it's not letting me fetch any data from document.

Thank you.

**Comment by chrismattmann** [comment]
I need a lot more information than what you have provided. I am wondering if your issue is the Java library installed? Are you able to use Tika Server doing a CURL post from the command line just to the backend server? What type of file are you posting? Is it a memory issue? What does the log file /tmp/tika-server.log print?

**Comment by chrismattmann** [comment]
if there is more detail and you find more out feel fee to list here in the comments.
